version: '3.7'

services:

  python:
    build: ./filebeat
    volumes:
      - ./logs:/usr/share/filebeat/logs

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    volumes:
      - ./elasticsearch/certs:/usr/share/elasticsearch/config/certs
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.12.1
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./filebeat/certs:/usr/share/filebeat/certs
      - ./filebeat/data:/usr/share/filebeat/data
      - ./logs:/usr/share/filebeat/logs
    environment:
      - ELASTIC_HOSTS=https://elasticsearch:9200
    depends_on:
      - python
      - elasticsearch
