filebeat.inputs:
- type: filestream
  enabled: true
  id: dummy
  paths: /usr/share/filebeat/logs/*.json
  parsers:
    - ndjson:
        keys_under_root: true
        overwrite_keys: true
        add_error_key: true
        expand_keys: true
  fields:
    index: "dummy"

#filebeat.autodiscover:
 #providers:
   #- type: docker
     #hints.enabled: true

#processors:
  #- decode_json_fields:
  #    fields: ["id", "state", "timestamp"]
  #- drop_fields:
  #    fields: ["agent", "ecs", "fields", "host", "input", "log"]
  #- add_cloud_metadata: null
  #- add_host_metadata: null

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "%{[fields.index]}"

setup.template.name: "app"
setup.template.pattern: "app-*"
