filebeat.inputs:
- type: filestream
  enabled: true
  paths: /usr/share/filebeat/data/dummy.json
  json.keys_under_root: true
  json.overwrite_keys: true
  json.add_error_key: true
  json.expand_keys: true
  fields:
    index: "dummy"

output.elasticsearch:
  hosts: ["localhost:9200"]
  #index: "%{[fields.index]}"
