filebeat.inputs:
- type: filestream
  enabled: true
  id: dummy0
  paths: /usr/share/filebeat/logs/dummy_0.json
  parsers:
    - ndjson:
        keys_under_root: true
        overwrite_keys: true
        add_error_key: true
        expand_keys: true
  fields:
    index: "dummy0"
- type: filestream
  enabled: true
  id: dummy1
  paths: /usr/share/filebeat/logs/dummy_1.json
  parsers:
    - ndjson:
        keys_under_root: true
        overwrite_keys: true
        add_error_key: true
        expand_keys: true
  fields:
    index: "dummy1"

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "%{[fields.index]}"

setup.template.name: "beat"
setup.template.pattern: "beat-*"
